### ISSUE TITLE
Import時に不足している情報を補完してほしい

### ISSUE THREAD

**Issue by t5ugu** [ChenCMD/Shape-Generator#28]
過去にExportされたものをImportするとき、プレビューが機能しない場合は、いずれかの図形の何らかの情報が不足している可能性があります。よって、不足している情報を補完することを求めます。

私の場合は、図形「線」の項目「オフセット」がない頃にExportしたものを、その項目が追加された後にImportしようとしましたが、プレビューが機能しませんでした。
しかし、Export当時と**同じ項目**で図形を編集することはできています。

各図形には無編集時のパラメーターが設定されているようなので、Importされた図形にパラメーターの不足が認められた場合、それらを応急的に埋め合わせるなどするようにして頂ければと思います。

**Comment by ChenCMD** [comment]
完全に忘れてた、すぐに修正します
