### ISSUE TITLE
Website doesn't render in Safari

### ISSUE THREAD

**Issue by MalbaCato** [ChenCMD/Shape-Generator#32]
There's little you can do with this, but I found the reason, so may as well document it.
The console prints `SyntaxError: Invalid regular expression: invalid group specifier name`, so in case another error pops up, I'm specifically talking about this one.
Several `eval()` layers deep in `bundle-1629955071417.js` something tries to create the following regex: `var key = text.match(/(?<=\[ImportKey\]: ).*(?=\r?\n)/);`. This is a fairly recent addition to the js spec, and Safari doesn't support it.
Here's the section of code that appears inside the innermost `eval()` where the error occurs 
https://codebeautify.org/jsvalidate/cb371d55, I hope this will help find the library where this originates from.

**Comment by ChenCMD** [comment]
This is too much of a terrible specification:(
Thanks to your detailed research, we have already identified the cause of the problem and will fix it immediately.

**Comment by MalbaCato** [comment]
oh, so it was in your code? these frameworks are so confusing :[
anyway, just tested and it indeed seems to work!
